# Generated by Django 2.0.7 on 2018-07-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
